### ISSUE TITLE
[terra-demographics-banner] Background image does not fully extend to container

### ISSUE THREAD

**Issue by yuderekyu** [cerner/terra-core#2079] opened 2018-11-30 21:23 UTC
# Bug Report
In some cases if a background image is set on `demographics-banner`, it does not extend to all borders. A 1 pixel line is visible on either the bottom or right side, depending on the size of the browser window.

Zoom in on the below screenshot. The `demographics-banner` background image is set to a linear gradient. Notice that the white doc template background bleeds through on the bottom of the `demographics-banner`.
<img width="1392" alt="screen shot 2018-11-30 at 3 16 01 pm" src="https://user-images.githubusercontent.com/14063284/49315366-1301ab80-f4b3-11e8-868c-cb42c47ef778.png">

Could be a browser rounding issue: https://stackoverflow.com/questions/28832046/background-size-leaves-a-one-pixel-line-to-the-right-of-my-browser

## Environment

* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Mac High Sierra on desktop

**Comment by JakeLaCombe** [comment] 2019-01-02 19:16
Can you provide the background style as part of this issue? It will make it easier to debug

**Comment by yuderekyu** [comment] 2019-01-02 20:56
Ah, I forgot to mention, this is when someone wants both a `background-color` and `background-image`. Add an inline background-image, and set it to some linear gradient.

<img width="1414" alt="screen shot 2019-01-02 at 2 37 08 pm" src="https://user-images.githubusercontent.com/14063284/50611443-0a2e3c00-0e9c-11e9-9149-53780f21e04d.png">

In this case, the background-image does not extend fully to the right. The dark background-color has ~ 1px  where there is no overlap.

Setting `background-clip: padding-box` fixes this case, but not the case in the initial screenshot. Checkout the clinical theme and [ocs-theme-variables branch](https://github.com/cerner/terra-core/compare/ocs-theme-variables#diff-2267f9efeef50e2d1511d46f3a178e10R1) for full styles to debug the initial screenshot

**Comment by supreethmr** [comment] 2019-01-31 14:07
This Issue seems to be fixed with PR : #2133 . no space / white line is being displayed in the demographics banner for the above specified scenarios.

**Comment by yuderekyu** [comment] 2019-01-31 16:01
@supreethmr hmm the issue persists within the internal clinical theme -  other styles in combination with `background-image` and  `background-color` may be creating this

**Comment by yuderekyu** [comment] 2019-02-01 14:50
@supreethmr emailed

**Comment by supreethmr** [comment] 2019-02-04 12:01
@yuderekyu  thank you with internal Clinical theme I was able to reproduce this issue. this issue seems to be due to demographics-banner padding value : padding: var(--terra-demographics-banner-padding, 0.714em);. Since it can be reproducible only with Clinical theme styles.

Since padding of demographics banner will be updated by custom property, --terra-demographics-banner-padding values assigned to this property in clinical Theme is creating white thin line at bottom of demographics banner. when Clinical Theme is not referred, custom property '--terra-demographics-banner-padding' will not have any value resulting in using fallback value of var() which is 0.714em as padding value for demographics banner and no spaces will shown up around the demographics banner.

Padding value for demographics banner was changed to clinical theme variable as part of PR #2133. we might need to change the bottom padding value of banner at Clinical Theme or we need to revert the changes done to padding property of banner in PR #2133.

**Comment by yuderekyu** [comment] 2019-02-06 15:22
@supreethmr 
hmmm, reverting reverting the padding back to `.714em` doesn't fix the issue. Seems like the bleed through pops up at different padding values, then disappears with others. 

In those cases, changing the `padding-bottom` value to a slightly smaller value than `padding-top` mitigates the issue, but doesn't fix the root cause. With `background-clip: padding-box` set, we expect `background-image` to extend to the outside edge of padding at all times, which isn't the case here. 

With that said, I'd be fine changing the clinical theme's `padding-bottom` to a different value, but we'll have to get UX input.

**Comment by neilpfeiffer** [comment] 2019-03-06 17:57
I'm thinking that simply changing the padding values might mask the issue with the current examples, but doesn't solve. 

Two reasons I would like to investigate further: 
1: the content can be variable the issue might present itself depending on rendered sizes  
2: we can't control all theme implementations, and could be present in other's usage

Suggestion might be a refactor (start with nothing and add banner elements one at a time) to identify exactly which element (and corresponding/combination styles) are causing the render bug to appear. Seems like @yuderekyu is right that something is affecting `background-clip` to not perform as expected.  Assumption is similar that it is the current combination of how flexes and margin/padding are being applied to trigger the problem.

**Comment by supreethmr** [comment] 2019-03-19 15:27
this issue seems to be due to the background image which is set using linear-gradient and image is not extending to full container resulting in 1px white line at bottom of demographics banner. 
 linear-gradient seems to be not being rendered by chrome as expected and the white line at the bottom of banner appear only at some browser window size not with all sizes like on external monitor or with mobile views.

Background-clip seems to be working fine. tried re-creating this issue with sample-app using clinical theme values for demographics banner not able to reproduce the issue. this issue seems to be appear only on examples docs. 

And also tried removing all the elements from demographics banner ' Demographics Banner with Gestational and Post Menstrural Ages ' 
<img width="1404" alt="Screen Shot 2019-03-19 at 6 39 37 PM" src="https://user-images.githubusercontent.com/12869809/54608321-791c3980-4a76-11e9-85ef-76ac7c58839a.png"> 

Even After removing all the elements from demographics banner white line still appears at the bottom of banner :
<img width="1382" alt="Screen Shot 2019-03-19 at 6 45 01 PM" src="https://user-images.githubusercontent.com/12869809/54608813-956ca600-4a77-11e9-83e1-fbbff9c03ad6.png">

To resolve the background image issue of not extending to it's container, With linear-gradient added 
-webkit gradient function to extend the background image fully to it's container : 
`background: -webkit-gradient(linear, left top, left bottom, from(#7bb5f1), to(#99cbfe));`

this seems to be fix the issue : 
<img width="1405" alt="Screen Shot 2019-03-19 at 6 47 43 PM" src="https://user-images.githubusercontent.com/12869809/54617517-63634000-4a87-11e9-90e0-3609cd74a578.png">

please share your suggestions to proceed further on these issue.

**Comment by supreethmr** [comment] 2019-03-20 06:24
I Noticed that padding value for demographics banner is not same for top and bottom unlike the padding value for right and left which are same both h

**Comment by yuderekyu** [comment] 2019-03-28 16:37
@supreethmr interesting. Autoprefixer should add prefixes to css attributes, so I wouldn't expect us to manually add it. Do we notice different behaviors in different browsers? I know this issue toggles depending on the screen + browser size. If it's actually a browser issue, then this is a `wont-fix`. I'll defer to UX on the padding question.

Perhaps fiddling with some background properties will get us further? https://stackoverflow.com/questions/14376328/background-sizecover-1px-whitespace-to-the-left?rq=1

**Comment by supreethmr** [comment] 2019-04-19 09:13
Could this be a box-shadow render error of browser. 

Since white line at Bottom of banner appears only with terra-clinical-theme. Clinical theme adds box shadow to banner which is not being added in terra-core theme so I am assuming this could be a box shadow rendering issue of browser's. 

I am not sure that this issue is caused by having box shadow but I have this below example where box shadow property is applied and 1px white line at the bottom of banner can be seen as shown below :

<img width="1680" alt="Screen Shot 2019-04-19 at 12 13 51 PM" src="https://user-images.githubusercontent.com/12869809/56411036-f36df280-629c-11e9-854e-5fe7c2e6ec87.png">

and removing box shadow removes white line from bottom of demographics banner too : 

<img width="1680" alt="Screen Shot 2019-04-19 at 12 14 48 PM" src="https://user-images.githubusercontent.com/12869809/56411066-1a2c2900-629d-11e9-9be1-7be9ecbd138b.png">

**Comment by yuderekyu** [comment] 2019-05-02 20:32
Gah weird. In these instances,`background-color` is set to transparent, while `background-image` is set to a gradient. If we set `background-color` to a non transparent value the white line disappears. I have no idea why.

I'm tempted to say inside the clinical theme, we set `--terra-demographics-banner-background-color` and `--terra-demographics-banner-deceased-background-color` to solid colors

**Closed** 2019-05-03 20:04 UTC
Labels: Needs UX review, Orion Reviewed, bug, demographics banner
