### ISSUE TITLE
[terra-form-fieldset] - There is no matching CSS for the isInline prop

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-core#1349] opened 2018-03-15 16:06 UTC
# Issue Description

The Fieldset has a first-class prop for allowing it to be set as inline. The `fieldset-inline` class that is applied as a result of this prop has no corresponding CSS that it maps to.

The class is applied: 
https://github.com/cerner/terra-core/blob/master/packages/terra-form-fieldset/src/Fieldset.jsx#L47

But there is no CSS:
https://github.com/cerner/terra-core/blob/master/packages/terra-form-fieldset/src/Fieldset.scss

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [X] Bug
- [ ] Other

## Expected Behavior

The isInline prop should apply a class that sets the component to display inline.

## Current Behavior

The isInline prop applies a class that has no associated CSS

## Steps to Reproduce

1. Create a terra-form-fieldset component.
2. Set isInline to be true.
3. Observe the component does not display inline.

## Environment

* Component Version:
* Browser Name and Version:
* Operating System and version (desktop or mobile):

**Comment by msaikaushik1992** [comment] 2018-03-16 16:03
@StephenEsser Actually the prop allowing it to be set as inline should be deprecated as discussed with @bjankord. The intention of that prop is for terra-form-field component to allowed to be set inline. So we can close this and reopen a new bug to deprecate the inline prop.

**Comment by bjankord** [comment] 2018-03-16 17:45
The expected behavior is that the fieldset does not provide an inline variation at this time. Looks like we removed the styles but missed removing the prop. I'm fine leaving this issue open and repurposing it for removing the prop. This change will be passive as the `isInline` prop does nothing now.

**Closed** 2018-03-19 18:26 UTC
Labels: bug, form-fieldset, orion reviewed

**Comment by bjankord** [comment] 2018-03-30 23:03
This is available in terra-form-fieldset@1.1.0
