### ISSUE TITLE
[terra-form-select] Mobile keyboard opens when selecting option with "search" variant

### ISSUE THREAD

**Issue by lawsonjames** [cerner/terra-core#2877] opened 2020-03-04 16:53 UTC
# Bug Report

## Description

When selecting an option with the "search" variant of terra-form-select, the keyboard will open after the option is selected. It seems like this would not be a desired behavior. Since the user has already selected an existing option it would follow that the user no longer has a need to search for other options.

## Steps to Reproduce
This behavior is reproducible using the "search" variant example on the [documentation page](https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/select) on mobile.

1. Open dropdown menu of options
2. Select an option
3. Keyboard is opened

## Expected Behavior
If an option is selected from the dropdown menu of options, I would expect the keyboard to not open for searching purposes.

## Environment

* Component Name and Version: terra-form-select with "search" variant
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): mobile

## @ Mentions

@neilpfeiffer 
@mjhenkes 
@yuderekyu

**Comment by neilpfeiffer** [comment] 2020-03-12 14:50
Closing as this is the intended behavior for the current component. 
(Adding to ideas list for considerations in Future Component)

_UX rationale:_
The `Search` and `Combo` varieties are functionally when you break them down -- a basic input element, placed beside a dropdown select element (shortened to just the arrow icon with no label). Because of this, the interactions with the overall component follow the same rules of the elements as individuals: when interacting with the input, it places focus in the input and causes the keyboard to appear, but when interacting on mobile with only with the dropdown via the button, since assumption is the user is intending to look through the list not search through the list, so the cursor is never placed in the input and therefore the keyboard does not appear. It is not until after making a choice that focus is put on the input and the cursor appears (triggering the keyboard), which allows users to clear the phrase, or adjust for the combobox variant. This is consistent with other similar libraries like [Semantic UI](https://semantic-ui.com/modules/dropdown.html) and [Kendo UI for Angular](https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/). I would not expect that the keyboard never appears after selecting an option from the list of the search & combobox variants however.

We will keep this interaction suggestion in mind though as we start to rebuild Terra select components with accessibility-first approaches, something that rather than treating the component as two separated units placed beside each other, instead the full unit (input plus down arrow) could be treated like a single button - something more like [Ant Design](https://ant.design/components/select/) or [Telerik for ASP.NET](https://demos.telerik.com/aspnet-ajax/combobox/examples/functionality/comboboxvsdropdownlist/defaultcs.aspx) where any click on any part of the search/combo box both opens the list and places focus in the input with a cursor, immediately triggering the keyboard, and therefore keeps the keyboard up before and after selecting an option and only removes the keyboard when the entire component loses focus. 

cc: @StephenEsser

**Closed by neilpfeiffer** 2020-03-12 14:50 UTC
Labels: Orion Reviewed, form-select

**Comment by lawsonjames** [comment] 2020-03-12 20:54
> when interacting with the input, it places focus in the input and causes the keyboard to appear, but when interacting on mobile with only with the dropdown via the button, since assumption is the user is intending to look through the list not search through the list, so the cursor is never placed in the input and therefore the keyboard does not appear.

@neilpfeiffer Can you confirm that the "search" variant is not meant to be used on mobile devices? I do not see this in any documentation.

**Comment by bb3284** [comment] 2020-03-13 16:45
@neilpfeiffer can you provide the location of the ideas list?  Who do I need to push on to make it happen?  The user experience with this component on mobile devices is not ideal, I think there needs to be more discussion about this.
