### ISSUE TITLE
Double lines are displaying using terra-divider

### ISSUE THREAD

**Issue by kehkasha16** [cerner/terra-core#2685] opened 2019-10-07 06:17 UTC
# Bug Report:
https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1569329349305?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1569329349305&teamName=Terra&channelName=Component%20Support&createdTime=1569329349305

## Description
In different machines and resolution sometime this divider is displaying like boxed.
Not only this we are loosing line on separator of tabs we are loosing at 75 % zoom and different resolution . 

## Steps to Reproduce
One can access the below URL:
https://usmlvv3bi0265.usmlvv1d0a.smshsc.net:3001/page_1

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/56245089/66288648-a12a9780-e8f7-11e9-9d8c-1ced1952eda3.png)

## Expected Behavior
The terra divider shall not appera as double lines

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by nramamurth** [comment] 2019-10-07 07:32
@kehkasha16 

You are talking about two different components - `terra-tabs` and probably `terra-menu`(?). Please have two issues explaining each issue in detail. 

Please provide us with reduced test samples for each problem that you mentioned in addition to providing details regarding the development environment - OS, browsers, resolution, devices, etc. I'd refrain from giving links to internal projects' codebase or their deployment.

**Comment by kehkasha16** [comment] 2019-10-09 12:00
@nramamurth  terra-divider

**Comment by ShettyAkarsh** [comment] 2019-10-14 08:27
@kehkasha16 could you please provide the OS, browser related information ?

**Comment by kehkasha16** [comment] 2019-10-14 08:51
We are using Chrome and IE browser

**Comment by ShettyAkarsh** [comment] 2019-10-15 04:48
we are not able to reproduce this in our local using chrome or IE browsers,  could you please confirm the version of the chrome or IE which you are using ?

**Comment by nramamurth** [comment] 2019-10-15 06:55
@kehkasha16 I'd like to reiterate this. 

Please provide us with reduced test samples for each problem that you mentioned in addition to providing details regarding the development environment - OS, browsers, resolution, devices, components, etc.

**Comment by neilpfeiffer** [comment] 2019-10-23 14:58
Reposting my comment from Teams conversation: 

> To be clear - the browser Zoom/Magnification Levels are not part of any responsive web strategy. RWD is an approach of how best to manage ever changing [screen size and orientation](https://www.nngroup.com/articles/responsive-web-design-definition/).  Terra currently does not test or support any zoom level other than 100%. 
\
As part of WCAG2.1, we will at some point start testing for [Reflow of any Text](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html), specifically when the browser zoom is set to 400%, checking to make sure all text appropriately does not get clipped or hidden. We have started preparing components to handle this, but we have not officially started testing and supporting this requirement yet.

**Comment by neilpfeiffer** [comment] 2019-10-23 15:53
Closing as 75% browser not supported by Terra at this time, in addition Chrome border zoom is a known browser bug https://bugs.chromium.org/p/chromium/issues/detail?id=834489

**Closed by neilpfeiffer** 2019-10-23 15:53 UTC
Labels: Needs more info, Orion Reviewed
