### ISSUE TITLE
Custom border-width in Structural Tabs breaking border-shorthand PostCSS properties transform.

### ISSUE THREAD

**Issue by PseudoFaux** [cerner/terra-core#1855] opened 2018-09-11 17:55 UTC
# Bug Report
Somewhat related to: Issue #1199 

## Description

When theming Structural tab borders, it was not working on the deployed site page. However, it does work when pulling down locally.
Pulling down locally:
![image](https://user-images.githubusercontent.com/7713715/45377781-39553080-b5c1-11e8-83c5-a4cb5f38b742.png)

Deployed site:
![image](https://user-images.githubusercontent.com/7713715/45377789-3f4b1180-b5c1-11e8-946a-b529eade846b.png)

In Issue #1199, it looks like we forced the borders to use the shorthand syntax when border-width, border-color, and border-style were all defined. However, this doesn't work in every case. The border-width property can use it's own shorthand syntax like `border-width: 0 1px 0 0;` This is not allowed in the border shorthand `border: 0 1px 0 0 solid #181b1d` as it is invalid CSS, thus not applying the styles.

## Steps to Reproduce

1. Write border styles as border-width, border-color, and border-style separately so that it compiles down to the shorthand-form. Ensure the border-width is of an invalid format for the shorthand form. (i.e. 0 1px 0 0 would do)
2. Run with production flag

## Expected Behavior

Structural tabs should be themeable.

## Possible Solution

Perhaps there can be a qualification for using the border shorthand property if the border-width shorthand is not used.

## Environment
* Component Name and Version: terra-tabs@3.21.0, (structural tabs)
* Browser Name and Version: All
* Node/npm Version: Node 8.9.4, npm 5.8.0
* Operating System and version (desktop or mobile): All

**Comment by bjankord** [comment] 2018-09-13 11:07
Hey @PseudoFaux, what theme are you working on? Also, can you share a link to your webpack config?  We were able to find the root cause of #1199. The issue we saw in #1199 was caused by [a bug in cssnano v3](https://github.com/cssnano/cssnano/issues/450) which is [a dependency in webpack's css-loader](https://github.com/webpack-contrib/css-loader/blob/master/package.json#L18). The bug has been fixed in [cssnano v4.0.0](https://github.com/cssnano/cssnano/releases/tag/v4.0.0). Also of note, [webpack's css-loader v1.0.0 release](https://github.com/webpack-contrib/css-loader/releases) also removed cssnano altogether. If you update to css-loader v1.0.0 in your webpack config, this issue you are seeing should go away.

**Closed** 2019-01-18 21:07 UTC
Labels: Orion Reviewed
