### ISSUE TITLE
Correct dynamic-grid Wiki Formatting

### ISSUE THREAD

**Issue by dwilhel1** [cerner/terra-core#1097] opened 2017-12-20 17:11 UTC
# Issue Description

**DynamicGrid Props Table** section of the [dynamic-grid](https://terra-ui.herokuapp.com/components/core/dynamic-grid) page is scrambled.

![screen shot 2017-12-20 at 10 59 24 am](https://user-images.githubusercontent.com/14366454/34218946-4e8c8592-e575-11e7-9b77-2abde464724a.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

Documentation bug.

## Expected Behavior

Table with information in the **DynamicGrid Props Table** section should be nicely formatted.

## Current Behavior

Upon viewing the wiki page for [dynamic-grid](https://terra-ui.herokuapp.com/components/core/dynamic-grid), some of the information in the **DynamicGrid Props Table** is scrambled.

## Steps to Reproduce

1. Navigate to [dynamic-grid](https://terra-ui.herokuapp.com/components/core/dynamic-grid) wiki page
2. View **DynamicGrid Props Table** section

## Environment

* **Component Version:** n/a
* **Browser Name and Version:**
    * Chrome Version 63.0.3239.84 (Official Build) (64-bit)
    * Firefox Developer Edition 58.0b11 (64-bit)
* **Operating System and version (desktop or mobile):** MacOS Sierra 10.12.6

**Comment by yuderekyu** [comment] 2017-12-20 19:01
Duplicate of #918 - routes researched include making `terra-props-table` parse through compiled code or changing `JSONStringify` to output with no whitespaces. With our current implementation, I vote the latter. The only issue is that markdown tables don't support column widths, so we have no control over the size of each column.

**Closed** 2017-12-20 20:28 UTC
Labels: duplicate, props-table, terra-ui.com
