### ISSUE TITLE
[Overlay] Not Appearing Above Navigation/Slide Panel Components

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1176] opened 2018-01-26 14:28 UTC
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Fullscreen overlay sshould appear above all components when rendered.

## Current Behavior
Full-screen overlays is actually blocking interaction on the screen as expected, however it visually does not appear to be above all components on the screen.
 
It appears the terra-slide-panel's panel component's z-index is set to 5000 in terra-site, while the overlay's is set to 100.

<img width="1236" alt="screen shot 2018-01-26 at 8 14 48 am" src="https://user-images.githubusercontent.com/14099737/35443922-59f8fad6-0272-11e8-9dba-13254553592a.png">

## Steps to Reproduce

1. Using terra-site v2.0.0-RC.0, start site 
2. Navigate to the Overlay Tests
3. Click any fullscreen tests

## Environment

* Component Version: v1.16.0
* Browser Name and Version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by noahbenham** [comment] 2018-02-26 14:54
This is a duplicate of https://github.com/cerner/terra-core/issues/963

**Closed** 2018-02-26 16:40 UTC
Labels: bug, orion reviewed, overlay
