### ISSUE TITLE
[terra-form-input] placeholder text does not display when control has focus in IE

### ISSUE THREAD

**Issue by po016255** [cerner/terra-core#2808] opened 2020-01-23 23:51 UTC
# Bug Report

## Description
When using the terra-from-select (and controls that wrap it such as terra-search-field) placeholder functionality, the control behaves differently in IE than in chrome/firefox.
In chrome/firefox when you give focus to the input box, the placeholder text is visible until you start typing. In IE, the placeholder text disappears as soon as the input box has focus.  This means that if focus is set by default, the user will never see the placeholder text unless they tab off the control.  Since mpages uses IE, this affects all terra components used within mpages.

## Steps to Reproduce
1. Open a any component in mpages or standalone ie.
2. If control has default focus, placeholder text is not visible.
3. If the control does not have default focus, the placeholder text is visible until the control is given focus.
4. Tabbing off a control restores the visibility of the placeholder text.

## Additional Context / Screenshots
The control is receiving default focus in both examples.

Chrome with correct behavior:  
![chrome_input_placeholder_behavior](https://user-images.githubusercontent.com/12768193/73033372-6b0e1680-3e07-11ea-8889-204a6a9e0318.gif)

IE with incorrect behavior:
![ie_input_placeholder_behavior](https://user-images.githubusercontent.com/12768193/73033383-7103f780-3e07-11ea-8337-f91ea6784788.gif)

## Expected Behavior
IE should mirror the behavior in chrome so behavior is consistent between the browsers.  Placeholder help text is used for user instruction and accessibility.  In chrome the JAWS screen reader will read the placeholder text.  In IE, it does not read it because it is not displayed.

## Possible Solution
This appears to be functionality not supported by IE10/11, so a manual workaround that only targets IE to mimic this behavior is most likely needed.  This is a thread with some ideas: https://stackoverflow.com/questions/14445891/keep-placeholder-on-focus-in-ie10

## Environment

* Component Name and Version:
** terra-form-input @ 2.31.0
** terra-search-field @ 3.33.0
* Browser Name and Version: IE10/11
* Operating System and version (desktop or mobile): Windows 10

**Comment by lokesh-0813** [comment] 2020-01-24 12:07
@po016255 terra-form-input is built on native html `input`. It's the default behaviour in Internet Explorer to not show placeholder for `input` after it has received focus.

**Comment by neilpfeiffer** [comment] 2020-01-27 04:12
@po016255 thanks for logging the issue. This is actually not a bug as the input placeholder are performing as designed. Terra has chosen to not create additional logic related to placeholders, but instead follow browser default behavior, including IE10/11. 


> Placeholder help text is used for user instruction and accessibility. In chrome the JAWS screen reader will read the placeholder text.

It is Cerner UX and Cerner Accessibility's recommendation _NOT_ to rely on placeholders for user instruction and guidance, but rather to always use a descriptive field `label`, and when needed, provide additional text to the `help` prop in all field compositions to provide help text that is accessible and always visible (and therefore always announced by JAWS). 

It has been well documented how problematic the placeholder attribute is in forms in terms of the lack of accessibility (color-contrast and to screen-readers), increase in difficulty for users to clearly recognizing an empty input, versus a completed input, versus a disabled input, in addition to the browser behavior inconsistencies:
- https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/
- https://www.nngroup.com/articles/form-design-placeholders/
- https://medium.com/simple-human/10-reasons-why-placeholders-are-problematic-f8079412b960
- https://webaim.org/techniques/forms/advanced#s-3
- https://www.smashingmagazine.com/2018/06/placeholder-attribute/
- https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research

\
\
For these reasons, UX will soon be removing all placeholders from all form elements: https://github.com/cerner/terra-core/issues/2712

Closing as not an issue.

**Closed by neilpfeiffer** 2020-01-27 04:12 UTC
