### ISSUE TITLE
Forms - Drop-down List

### ISSUE THREAD

**Issue by WhiteLight1107** [cerner/terra-core#733] opened 2017-08-16 18:52 UTC
# Issue Description
Create Forms - Drop-down List component.

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Provides a drop-down list to be used in consumer applications

## Current Behavior
Should Replace Select Field

**Comment by WhiteLight1107** [comment] 2017-08-16 18:54
# Tech Design for Card
## Summary:
The Card Component is used as a container for other divs. 

PR:
TBD

## React Props:
### Card:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| padding | array or bool | true | option to pass in a single boolean to turn on/off, or an array to specify each side using css short hand https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties |
| children | node | none | Child Nodes |

## Example:
```
import React from 'react';
import Card from 'terra-card';

const CardDefault = () => (
  <div>
    <Card>Hello World!!</Card>
</div>
);

export default CardDefault;

```

## CSS Classes:
| Selector | Description |
|----------|------|
| .well-card | Outer Container of the Card |
| .well-card-container | Inner part of the card used to contain children prop |
| .u-pa--sm | 10px padding |
| .u-pv--sm | 10px padding vertical |
| .u-ph--sm | 10px padding horizontal |
| .u-pt--sm | 10px padding top |
| .u-pb--sm | 10px padding bottom |
| .u-pl--sm | 10px padding left |
| .u-pr--sm | 10px padding right |

**Comment by tm4027** [comment] 2017-08-25 15:25
Orion JIRA created

**Comment by bjankord** [comment] 2017-10-13 20:50
Duplicate of #880

**Closed by bjankord** 2017-10-13 20:50 UTC
Labels: form, select, tech design
