### ISSUE TITLE
Status View glyph does not always display when it should

### ISSUE THREAD

**Issue by chris-bert** [cerner/terra-core#1752] opened 2018-08-01 20:28 UTC
# Bug Report

## Description
The Status View component contains logic that attempts to determine if the component has enough space to display the glyph.  In some cases, the glyph is not displayed even when there should be enough room for it.  This has been observed specifically in cases when the browser zoom level is changed.  The following link can be used to recreate the issue:

https://pages.github.cerner.com/healtheintent/action_plan/?knob-icon=plan&knob-title=Activities%20To%20Do&knob-subheading=5%20of%208%20activities%20need%20to%20be%20completed&knob-content=Card%20content&selectedKind=Components%2FNoActivitiesCard&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

## Steps to Reproduce
1. Using Chrome browser on desktop, set browser zoom level to 100%
2. Click on link above [a component using Status View should display with a glyph]
3. Set browser zoom level to 125%
4. Refresh browser [the component is displayed again this time without the glyph]

## Additional Context / Screenshots
![noactivitiescard snapshot - with icon](https://user-images.githubusercontent.com/25351504/43546978-f0cf5266-95a7-11e8-95d6-e12cb3bccddd.png)
![noactivitiescard snapshot - no icon](https://user-images.githubusercontent.com/25351504/43546982-f3499f4c-95a7-11e8-8a24-78fdb1f66811.png)

## Expected Behavior
The glyph should alway be displayed regardless of the browser zoom level when there is no restriction placed on the height of the StatusView component.

## Possible Solution
Change the logic that determines whether to display the glyph to be a little more forgiving.  Allow the calculated height of the StatusView contents to be 1 to 2 px greater than the height of the container.  At different zoom levels the calculated height of nodes can change slightly, probably due to the fact that offsetHeight used in the calculations is a rounded value.

## Environment
* Component Name and Version: terra-status-view v2.20.0
* Browser Name and Version: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
* Node/npm Version: Node: 8.9.2 / yarn 1.3.2
* Webpack Version: 3.12.0
* Operating System and version (desktop or mobile): OS X El Capitan version 10.11.6

**Comment by ShettyAkarsh** [comment] 2018-11-21 10:53
I have assigned this issue to myself.

**Comment by ShettyAkarsh** [comment] 2018-11-28 20:35
we are not able to recreate this issue in our terra code. can you please check and  let us know whether this issue exists in your production code as well ?

**Comment by bjankord** [comment] 2018-11-28 20:40
I'm unable to reproduce this issue on our doc site as well: https://engineering.cerner.com/terra-ui/#/components/terra-status-view/status-view/status-view

But I am able to reproduce it in [the link you provided](https://pages.github.cerner.com/healtheintent/action_plan/?knob-icon=plan&knob-title=Activities%20To%20Do&knob-subheading=5%20of%208%20activities%20need%20to%20be%20completed&knob-content=Card%20content&selectedKind=Components%2FNoActivitiesCard&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs) I believe there is something outside of the terra code causing the issue as we are unable to reproduce it on the doc site.

**Comment by chris-bert** [comment] 2018-11-28 21:15
I am able to reproduce this for several examples on the doc site by setting the zoom level to 110% and refreshing the browser.

**Comment by bjankord** [comment] 2018-11-28 21:48
I am able to reproduce on https://engineering.cerner.com/terra-ui/#/components/terra-status-view/status-view/status-view with zoom level set to 110% and 200%

@ShettyAkarsh we'll need to dig into this issue some more.

**Comment by ShettyAkarsh** [comment] 2018-11-29 16:16
Yes, this issue is reproducible when the zoom level is set to 110% and 200%. this will be fixed as part of general refactoring planned for this component.

**Comment by ShettyAkarsh** [comment] 2018-12-05 22:08
This issue occurs when the outer Div container (i.e which contains the status view component) height is not set and the default height value (which will usually be in the range of 250-300 pixels) is inherited from its parent container . 

Here basically the inner view which basically holds the status view components (i.e message, title, glych etc) has the  height value lesser than the total height calculated taking each individual component inside the inner view. so the below condition fails and the glych icon component is not displayed in the DOM.

if (viewHeight < (componentsHeight + this.glyphNode.offsetheight))
{
     DisplkayGlychIcon 
}

The difference in which the condition fails is usually just by 1 pixels or lesser. as the status view components inner divs adjust to the height of its parent container. which traverse back to the main div container of the status view.  if the height of the main div container is not set this issues occurs at certain resolutions.

as the above provided link is not opening  just wanted to know here. so is the height value set for the outer div container of the status view in this case ? if height value is set for the outer div then, can you please let us know what is the height value ?

**Comment by yuderekyu** [comment] 2019-01-18 21:41
@ShettyAkarsh are you still investigating this?

**Comment by yuderekyu** [comment] 2019-01-23 17:22
To me, the first option obscures the issue more than the second.

Adding to the 2nd option, we could use the `toFix()` method to cap precision instead of redistributing size values. From my testing, rounding occurs @ the 0.00000x place.

Here's a snippet of what I'm thinking:
```jsx
/* For 'final' size values, cap precision to the hundredth value. This stops rounding issues that occur when browsers are at non default zoom values*/
    const statusViewHeight = this.innerNode.getBoundingClientRect().height.toFix(2);
    const statusViewWidth = this.innderNode.getboundingClientRect().width.toFix(2);
    
    let glyphHeight = this.glyphNode ? this.glyphNode.getBoundingClientRect().height.toFix(2) : 0;
    let glyphWidth = this.glyphNode ? this.glyphNode.getBoundingClientRect().width.toFix(2) : 0;
    let titleHeight = this.titleNode ? this.titleNode.getBoundingClientRect().height : 0;
    let actionsHeight = this.actionsNode ? this.actionsNode.getBoundingClientRect().height : 0;
    let messageHeight = this.messageNode ? this.messageNode.getBoundingClientRect().height : 0;
    let dividerHeight = this.dividerNode ? this.dividerNode.getBoundingClientRect().height : 0;

    contentHeight = (titleHeight + actionsHeight + messageHeight + dividerHeight).toFix(2);
    contentWithGlyphHeight = contentHeight + glyphHeight;

    if (this.glyphNode && statusViewHeight >= contentWithGlyphHeight && statusViewWidth >= glyphWidth) {
      showGlyph = true;
      if (!this.props.isAlignedTop) {
        const remainingHeight = statusViewHeight - contentWithGlyphHeight;
        paddingTop = remainingHeight * 0.4;
        paddingBottom = remainingHeight * 0.6;
      }
    } else if (!this.props.isAlignedTop){
      const remainingHeight = statusViewHeight - contentHeight;
      paddingTop = remainingHeight * 0.4;
      paddingBottom = remainingHeight * 0.6;
    }
```

**Comment by ShettyAkarsh** [comment] 2019-01-24 13:37
@yuderekyu, I had tried rounding using .toFixed() for multiple precisions along with 2, for the above logic before. but it was not consistent across all the resolutions.  some or the other resolutions still have the same above issue and also using .toFixed() rounds the number to the provided decimal precisions and returns as a string. we need to again convert it back to number.

**Comment by yuderekyu** [comment] 2019-01-25 15:20
@ShettyAkarsh awww darn - your second option should be good then

**Comment by ShettyAkarsh** [comment] 2019-01-28 05:04
Thanks @yuderekyu. i will log a PR for this using the second option.

**Closed** 2019-02-18 19:12 UTC
Labels: Orion Reviewed, bug, status view
