### ISSUE TITLE
[terra-form-select] Dropdown over header while scrolling the view

### ISSUE THREAD

**Issue by sudharshanv1992** [cerner/terra-core#2942] opened 2020-04-24 15:57 UTC
# Bug Report

## Description

Dropdown over the header while scrolling the view
![DropdownOverHeader](https://user-images.githubusercontent.com/28642254/80232140-0b2b4400-8672-11ea-9d47-e361dee82778.gif)

## Steps to Reproduce

https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/select
1. click on the select
2. scroll the view
3. can see the dropdown over the header.

## Environment

* Component Name and Version:
* Browser Name and Version: google chrome 80.0.3987.163
* Node/npm Version: [e.g. Node 8/npm 5] Node 8.9.2
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by shinepd** [comment] 2020-04-24 16:03
Related to #2892 - In this instance, we have a sticky header the control floats under. When scrolling, without the drop-down closing, the scroll-box floats over the header.

**Comment by StephenEsser** [comment] 2020-04-24 16:08
@sudharshanv1992 @shinepd

This has been brought up a few times. The current z-index strategy places the dropdown above the header and is expected behavior. The scrolling behavior is necessary for mobile applications because the presence of the keyboard overlaying the screen.

We can leave this issue open for a little more discussion but we'll need more feedback. Do you think the dropdown should display under the header, close on scroll, or prevent scrolling entirely?

**Comment by sudharshanv1992** [comment] 2020-04-24 17:50
@StephenEsser 
I think we can close  the dropdown on the scroll.

**Comment by StephenEsser** [comment] 2020-04-24 18:00
I don't think it's guaranteed the dropdown will never be in a situation on the screen where scrolling might be necessary to reveal more options. We've started work to introduce a native select that might resolve a few of these concerns. This will shift the majority of accessibility/behavior concerns into the native select.

Here's a PR if you'd like to demo/view the anticipated changes:

https://github.com/cerner/terra-core/pull/2934

**Comment by shinepd** [comment] 2020-04-24 18:52
@StephenEsser it looks like the new native control certainly alleviates concerns around scrolling while a drop-down is open; however, it will be quite a bit of work for us to migrate to use this new control. I know we've had discussions in the past about supporting our unique requirements (such as the ability to limit a multi-select to a single option if the first option is selected) due to data model constraints. Long term, I do think we will switch to the native control, provided we're able to meet all of our requirements in some form. Would it be possible/advisable for us to manage closing the dropdown onScroll ourselves?

**Comment by StephenEsser** [comment] 2020-04-28 16:43
@shinepd It would be possible to manage closing the dropdown on scroll, but it wouldn't be advisable. The custom implementation would create an inconsistent behavior within the application and may cause problems on mobile. On mobile the keyboard can potentially cover part of the dropdown. Without scrolling it may be possible to have options that the user can never interact with.

Can you provide a few more details about the requirements and impact this has had on your application? 

*small disclaimer about open source, feel free to message internally if anything is proprietary*

Is this creating a potentially hazardous situation, hiding demographics information, is it cosmetically unappealing, or potentially causing other issues?

**Comment by shinepd** [comment] 2020-04-29 00:24
Sure, here are some high-level bullets (some have been omitted that I can message you about):
* Allowance of one and only one freetext entry
* Prepension of "Other: " to freetext response
* Ability to hard stop at a certain character count as well as provide an error message

I'm certain our consumption of the current terra-form-select does not meet accessibility requirements. We've hard locked to quite an old version in order to satisfy our requirements through some additional logic we've added on top of the control. Utopia for me would be first class (or as close as we can get) support for these requirements in the new native control to ease all of our concerns.

**Comment by shinepd** [comment] 2020-04-29 21:34
Our application's primary use right now is desktop, though we do have plans for mobile in the not-so-distant future. For this issue, I think it is just cosmetically unappealing / confusing to the end user. 

@at014421 do you want to weigh in here as well with respect to impact on our application with the drop-down remaining open on scroll?

**Comment by at014421** [comment] 2020-04-29 21:46
Agree it is probably more cosmetic and looks sloppy as @shinepd stated, but there could be a chance it could cover up important information depending on the content and situation.  I don't think the risk is super high though since I believe it's fairly obvious that its still open and the user can click out of it to close it, correct?

**Comment by jeremyfuksa** [comment] 2020-04-30 22:44
Hi, all. I'm chiming in with the perspective of the UX team.
It looks like @StephenEsser has done a pretty good job addressing the various UX pitfalls with different possible solutions. My advice is to adopt the native control when it is available to ensure that your control is accessible while also addressing the aesthetic concerns you have at the mobile breakpoint.
If you have any additional questions or comments, I'd love to hear them.

**Comment by ryanthemanuel** [comment] 2020-05-04 14:51
Per @jeremyfuksa and @StephenEsser's comments, closing this.

**Closed by ryanthemanuel** 2020-05-04 14:51 UTC
Labels: Needs design input
