### ISSUE TITLE
Collapsible Menu View visible re-render

### ISSUE THREAD

**Issue by cwalten** [cerner/terra-core#1034] opened 2017-11-21 19:00 UTC
# Issue Description
Collapsible Menu view re-renders once the component calculates its needed space. However, recently we have noticed the re-render has become visible (see attached gif). In fact, on a Windows machine running Edge, we can see each individual button get collapsed one at a time (though this might be a slightly separate issue).

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
It would be expected that the control would not be visible until the re-render was complete, saving the user from experiencing a jumpy feeling UI on load.

## Current Behavior
The component is visible before re-render then jumps to a collapsed view.

## Steps to Reproduce
1. See gif

## Environment

* Component Version: 1.5.0
* Browser Name and Version: Edge and Chrome
* Operating System and version (desktop or mobile): Windows and Mac

![ButtonRendering](https://user-images.githubusercontent.com/19825717/33091143-dcccff06-cebb-11e7-9153-b36f21eeda9b.gif)

**Comment by jmsv6d** [comment] 2017-11-28 18:49
@cwalten Can you verify what version of collapsible menu view you are using? This was an issue in v1.0.0 but should have been solved here https://github.com/cerner/terra-core/issues/867, the collapsible menu view is now hidden until width calculations are complete, this fix was released in v1.1.0 It looks to still be functioning correctly on our engineering site.

**Comment by cwalten** [comment] 2017-11-28 19:38
@jmsv6d Our package.json requests "terra-collapsible-menu-view": "^1.4.0", and the package-lock confirms this version. It is happening in our CI deployed master build.

**Comment by dkasper-was-taken** [comment] 2017-11-28 22:15
@cwalten Are you using the same lists and item rows when switching between your worklists? This could potentially lead to the same collapsible menu view being used, and just the props updating. Triggering a new render, but not a new mounting. Thus the flicker.

**Comment by mjhenkes** [comment] 2017-11-30 19:17
@cwalten have you been able to check into @dkasper-was-taken's question?

**Comment by cwalten** [comment] 2017-12-01 20:11
@dkasper-was-taken When the filter is changed, we update our Store and subsequently re-render with the new props, filtering which items get rendered and which do not. The keys however would be the same as they are based off of the data the row represents, irrelevant of the filter. I am not sure the consequences here of that decision, could you elaborate?

//cc @mjhenkes

**Comment by jmsv6d** [comment] 2017-12-21 18:23
@cwalten If you're using the same list and item rows then the collapsible menu view is not getting remounted. The flicker is likely the collapsible menu view getting re-rendered with new props, not the resizing. We are already hiding the collapsible menu view during the initial render used for width calculations, so I believe that reusing the list and item rows is likely the cause of the issue.

**Comment by jmsv6d** [comment] 2018-01-03 21:04
Closing as it appears this issue doesn't lie in the Collapsible Menu View component and no additional feedback has been given.

**Closed by jmsv6d** 2018-01-03 21:04 UTC
Labels: bug, collapsible-menu-view, orion reviewed
