### ISSUE TITLE
SelectField - can't call getBoundingClientRect on undefined error

### ISSUE THREAD

**Issue by david-hibshman-cerner** [cerner/terra-core#1541] opened 2018-05-26 06:02 UTC
# Issue Description
Copying the example code from [Terra Github SelectField Example](https://github.com/cerner/terra-core/blob/master/packages/terra-form-select/examples/test-examples/SelectField.example.jsx) - without using the _placeholder_ or _defaultValue_ attributes - throws the above error every time I click on the rendered select elements textbox to display the options.

I believe this is similar to this [FB logged issue](https://github.com/facebook/react/issues/5447).  The issue appears to be the `componentDidUpdate` function in the _Frame.jsx file as demonstrated in the following code block:
```javascript
// broken version
componentDidUpdate(previousProps, previousState) {
    // this.dropdown is a ref on the dynamically rendered Dropdown component
    // Unfortunately it's undefined - probably because it hasn't rendered on screen yet
    if (Util.shouldPositionDropdown(previousState, this.state, this.dropdown)) {
      clearTimeout(this.debounceTimer);
      // looks like dev already had suspicions it wasn't displaying immediately
      this.debounceTimer = setTimeout(this.positionDropdown, !previousState.isOpen ? 0 : 100);
    }
}
```
If I change it as follows things work ok:
```javascript
// fixed version - not a fan of the setTimeout use here - but for demonstrating the
// problem - pulling the Util.shouldPositionDropdown conditional check into
// the setTimeout seems to be OK
componentDidUpdate(previousProps, previousState) {
    this.debounceTimer = setTimeout(function() {
        if (Util.shouldPositionDropdown(previousState, this.state, this.dropdown)) {
          clearTimeout(this.debounceTimer);
          this.positionDropdown();
        }
      }.bind(this), !previousState.isOpen ? 0 : 200);
}
```

## Issue Type
- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
* It should show the options without crashing my app.
* If possible, maybe consider just rendering the options once and then showing or hiding as needed to avoid the setTimeout all together.  _This is suggest with little or no thought given to other concerns that probably exist._

## Current Behavior
* It doesn't show the options and crashes my app.

## Steps to Reproduce
1.  Copy sample code linked to above and run it
2. Open the browser's Dev Tools/JS console
3. Click with the mouse on the rendered select element's text box
    1. Not sure of clicking the arrow exhibits this behavior or not, but should be considered.
4. App will crash
5. View the reported _undefined_ message in the browser console.

## Environment
* Component Version:
    * terra-form-select/lib/SelectField v. 4.1.0
* Browser Name and Version:
    * Chrome: 66.0.3359.181 (Official Build) (64-bit)
    * IE 11 (x64):  11.125.16299.0 Update Version:  11.0.49  (KB4052978)
    * MS Edge:   41.16299.15.0 EdgeHTML 16.16299
* Operating System and version (desktop or mobile):
    * Developer Desktop ruuning Windows 10 64-bit 1709 (OS Build 16299.125)

**Comment by StephenEsser** [comment] 2018-05-26 14:57
Hi @david-hibshman-cerner,

I am unable to reproduce the issue given the steps you provided. Here is the exact code I am running to try and reproduce:

```
import React from 'react';
import SelectField from 'terra-form-select/lib/SelectField';

const SelectFieldExample = () => (
  <SelectField label="T-shirt size" selectId="select-field">
    <SelectField.Option value="xSmall" display="Extra Small" />
    <SelectField.Option value="small" display="Small" />
    <SelectField.Option value="medium" display="Medium" />
    <SelectField.Option value="large" display="Large" />
    <SelectField.Option value="xLarge" display="Extra Large" />
  </SelectField>
);

export default SelectFieldExample;
```

Can you provide the code you are running and the version of React so we can cross reference?

For the additional concerns you posted. The debounce timer is used to debounce height and position calculations of the dropdown menu. It's not there to wait until an element is visible. This largely comes into play when the browser is resizing, worst case scenario a user is manually dragging the window to be larger and smaller repeatedly causing the dropdown to position and rerender many times. This simply waits for the resizing to finish for a set amount of time before performing the calculation instead of performing it on every tick during during the resize.

**Comment by david-hibshman-cerner** [comment] 2018-05-28 02:51
It’s largely the same except I am using a class instead of a function.

I can never actually get it to work, it always fails with this.dropdown ref being undefined.

I realize debounce isn’t a sensible application for waiting for it to draw, but it was a cheap way to get a free timeout to verify the problem quickly.  I probably should have explained that better in the ticket.  The point is if I add a small timeout to wait for it to be visible then it works for me.

I am using React 16.0.0.  I see in the docs 16.2.0+ is mentioned.
I upgraded React and React-Dom to 16.2.0.  I updated every other component that I have in my node_modules folder up and down the dependencies tree start with terra-form-select.
Now I get the error below.  Maybe I missed a dependency somewhere

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Hookshot`.
    at invariant (invariant.js:42)
    at createFiberFromElement (react-dom.development.js:5753)
    at reconcileSingleElement (react-dom.development.js:7531)
    at reconcileChildFibers (react-dom.development.js:7635)
    at reconcileChildrenAtExpirationTime (react-dom.development.js:7756)
    at reconcileChildren (react-dom.development.js:7747)
    at finishClassComponent (react-dom.development.js:7881)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)




import React from 'react';

import SelectField from 'terra-form-select/lib/SelectField';



class MyForm extends React.component {

  handleSubmit(evt) {

    evt.preventDefault();

    alert(“Selected Value:  “ + evt.target.value);

    return true;

  }



  render() {

     return

       <form onSubmit={this.handleSubmit.bind(this)}>

         <SelectField label="T-shirt size" selectId="select-field">

           <SelectField.Option value="xSmall" display="Extra Small" />

           <SelectField.Option value="small" display="Small" />

           <SelectField.Option value="medium" display="Medium" />

           <SelectField.Option value="large" display="Large" />

          <SelectField.Option value="xLarge" display="Extra Large" />

         </SelectField>

       </form>

     );

  }

}



export default MyForm;

**Comment by StephenEsser** [comment] 2018-05-28 03:38
Hi @david-hibshman-cerner 

At a real quick glance I noticed `React.component` is lowercase and should be `React.Component`.

**Comment by david-hibshman-cerner** [comment] 2018-05-29 03:32
That from me typing from memory, not a cut-and-paste of actual code.

**Comment by StephenEsser** [comment] 2018-06-21 14:08
Closing this issue as not reproducible. I confirmed a few projects have managed to use the SelectField without seeing this error. This could potentially be caused by two version of React being loaded at once.

**Closed by StephenEsser** 2018-06-21 14:08 UTC
Labels: Needs more info, Orion Reviewed
