### ISSUE TITLE
Horizontal Rule / Divider Component

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-core#382] opened 2017-05-22 19:16 UTC
# Issue Description
We want to provide a component to easily create a horizontal divider. 

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
A react component which renders a horizontal rule. It should have props to change the color of the ruler and the height of the rule. By default, the height should be 1px.

**Comment by bjankord** [comment] 2017-10-16 15:07
Here is some sample markup to render with the react component

```
<hr class="divider" />
```

and here is some sample css to go with it

```
.divider {
    border: 0 solid;
    border-top: 1px solid #dedfe0;
    margin: 0;
    height: 0;
}
```

**Comment by msaikaushik1992** [comment] 2017-10-17 18:19
# Tech Design 
## Summary:
The horizontal rule/divider component is a component that is used to separate content on a layout.

## Responsiveness:
N/A

## Accessibility
N/A

## React Props:
N/A

## Theme-able styles:
borer-color
border-width

**Comment by bjankord** [comment] 2017-10-17 21:51
+1 on tech design.

**Comment by mjhenkes** [comment] 2017-10-17 21:55
+1

**Comment by JakeLaCombe** [comment] 2017-10-19 14:14
+1. Is it possible to move this to our internal tech designs repo as well?

**Comment by msaikaushik1992** [comment] 2017-10-30 17:18
After discussing in the war room about this, we all decide to use github issues itself for tech-design unless the issue is too complex @JakeLaCombe

**Comment by emilyrohrbough** [comment] 2017-11-02 14:08
Resolved in #962

**Closed by emilyrohrbough** 2017-11-02 14:08 UTC
Labels: divider, new feature
