### ISSUE TITLE
terra-form-checkbox alignment issue

### ISSUE THREAD

**Issue by leducquan** [cerner/terra-core#2807] opened 2020-01-23 18:12 UTC
# Bug Report

## Description
Terra checkbox seems to be having a centre alignment issue. It does not centre align correctly within a div.

Please see code sandbox for example when compared to a normal checkbox type.

https://codesandbox.io/embed/delicate-grass-b5xcb

## Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/19377430/73011136-909d1f00-3e0b-11ea-93d5-1d43eab742a8.png)

## Expected Behaviour

Should align correctly.

**Comment by neilpfeiffer** [comment] 2020-01-27 02:35
@leducquan - Thanks for logging the issue - this is actually not a bug. The current form-checkbox was designed to be used with labels in the format of the traditional form/questionnaire, so it contains space the the right and below built in to appropriately space between each row. 

Closing as there already is a previous issue logged to create a new "standalone" version, for use not in the questionnaire style forms, which would remove the built-in space like shown above, and any needed additional accessibility items: https://github.com/cerner/terra-core/issues/2197

**Closed** 2020-01-27 02:36 UTC

**Comment by neilpfeiffer** [comment] 2020-01-27 02:41
@leducquan if you have a specific need for the standalone checkbox variety, contact me and we'll work through the details.
