### ISSUE TITLE
Specifying Lerna Version in lerna.json

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#1282] opened 2018-02-23 19:22 UTC
# Issue Description
We need to look into how we specify our Lerna version in the lerna.json file. 
![screen shot 2018-02-23 at 1 20 13 pm](https://user-images.githubusercontent.com/14099737/36612486-55d145ae-189c-11e8-8f31-afa768a3cc9e.png)

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by yuderekyu** [comment] 2018-10-03 16:48
At this moment, lerna is on version 3.4.0. List of 3.0 breaking changes: https://github.com/lerna/lerna/releases/tag/v3.0.0

**Comment by yuderekyu** [comment] 2018-10-03 17:02
Duplicate of https://github.com/cerner/terra-core/issues/1792

**Closed by yuderekyu** 2018-10-03 17:02 UTC
Labels: Orion Reviewed
