### ISSUE TITLE
Create Toggle-Preview-Text Component

### ISSUE THREAD

**Issue by gabeparra01** [cerner/terra-core#1785] opened 2018-08-22 18:48 UTC
# Feature Request

## Description
Create a new Toggle Preview Text display component that will show a preview of a set of text or the full set of text. Text will be passed to this component. If the number of characters in the text surpasses a certain value, then only part of text will be displayed to the user. The user can then click a "see more" link that will display all of the text that was passed into the component. After that action, the link will then be displayed as "see less" and the user can click on it again to only display part of the text and the link will be changed back to "see more".

This component will help save space when the page uses large text inputs that are not always the main focus of the user. It would be especially beneficial in slide panels and modals.

The component could be designed to allow the user to pass in the character limit or it could use a constant value as the character limit so that it looks the same across all Orion applications. I am open to whichever direction the Terra Team wants to take on the character limit.

## Additional Context / Screenshots
Here are some screenshots of the design I have right now. It uses the Terra Toggle Button and imports terra-button for the de-emphasis styling:
![image](https://user-images.githubusercontent.com/42552940/44483879-de5b9980-a611-11e8-86ed-6eb5c3be6a72.png)

Screenshot for after the user clicks the the "see more" link:
![image](https://user-images.githubusercontent.com/42552940/44483914-f501f080-a611-11e8-9804-0a75a03cfc52.png)

**Comment by bjankord** [comment] 2018-08-22 19:43
There is a [related issue logged](https://github.com/cerner/terra-core/issues/1563) for creating a component with similar functionality. Issue #1563 is a placeholder as we wait to start work on the OCS show / hide component. It looks like you may have done some prior work on this functionality based on the screenshots, would you be interested in contributing development work to complete this component in terra-core?

**Comment by gabeparra01** [comment] 2018-08-22 20:00
@bjankord I am planning submit a design/pull request if this feature request is approved. Do you know when issue #1563 will have Orion requirements? Will that component be utilizing terra-toggle-button to show/hide?

**Comment by bjankord** [comment] 2018-08-22 20:15
I need to check with our UX designer, @neilpfeiffer and see if the design for the OCS show/hide component is finalized. Then will use that design to drive functionality/implementation.

**Comment by gabeparra01** [comment] 2018-08-23 21:41
I talked with @neilpfeiffer and he agreed that this issue is a dupicate of #1563. I will be working on the solution to both of these

**Comment by yuderekyu** [comment] 2018-09-17 14:05
Closing, duplicate of #1563

**Closed by yuderekyu** 2018-09-17 14:05 UTC
Labels: Needs Orion Requirements, Orion Reviewed
