### ISSUE TITLE
List adding accordion section headers

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-core#1321] opened 2018-03-07 13:52 UTC
## Summary
- Enhance list to be able to add expanding & collapsing section-headers as a new subcomponent list type with its own props.
- Will follow and extend work done for #1320 static section-headers 
- will be fully themeable using existing patterns
- will be similar/related to #1270 stand-alone Section Header

## Issue Type

- [x] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Screenshot of new expanding/collapsing section headers in list (visual details provided separately):

![image](https://user-images.githubusercontent.com/1355485/37095683-3714379a-21dc-11e8-85d9-9e2b0ab138b0.png)

----
# Tech Design `terra-list/lib/(add)`

## React Props:
_(add table or list changes)_ 

## Themeable Styles:
_(add)_

## Responsiveness:
_(add)_

## Interaction States:
_(add)_

## Accessibility:
_(add)_

## i18N / Bi-directionality:
_(add)_

## Example: 
_(add if needed)_

## Notes: 
_(add if needed)_

## Changes:
_(add if needed)_

## Questions:
_(add if needed)_

**Comment by emilyrohrbough** [comment] 2018-03-08 16:48
Duplicate of #996?

**Comment by noahbenham** [comment] 2018-08-10 14:27
Will this include infinite list support?

**Comment by dkasper-was-taken** [comment] 2018-09-03 16:51
@noahbenham The revised design of the list sections will be supported within the infinite list, but large list sections have the ability to hurt reduce the efficiency of the infinite list. As such, I don't know if we have a recommended usage for this yet.

**Comment by dkasper-was-taken** [comment] 2018-09-03 17:04
Additional design considerations:

No animations of the height value should be introduced as both framerate and react rendering problems would be introduced. Animations would also prevent section usage within the infinite list.

Collapsed sections should be virtualized. Large data sets should take advantage of the ability to increase page performance when collapsing sections.

The toggled collapsed state should be externally managed, thus sections are controlled components.

List should have no concept of collapsed state. The only way this should be introduced is if collapsed state needs to be linked to other sections as a consistent design pattern. Similar to selection logic. Though a helper function could likely help a consumer instead of state.

**Comment by dkasper-was-taken** [comment] 2018-11-06 19:42
Update on the design, infinite list will be able to have headers and subheaders, but collapsible sections will not be supported within the infinite list.

**Closed** 2019-02-11 15:20 UTC
Labels: Needs Orion Requirements, Orion Reviewed, enhancement, list, new feature
