### ISSUE TITLE
ToggleSectionHeader: isTransparent bug with List and button in IE

### ISSUE THREAD

**Issue by celvro** [cerner/terra-core#1799] opened 2018-08-28 17:54 UTC
# Bug Report

## Description

In Internet Explorer when ToggleSectionHeader has isTransparent property, and contains a button, and is within a List.Item, extra space appears at the end of the component when moving the mouse around.

This does not happen without the isTransparent property.

I've also found clicking the button removes this extra space, but hovering over the section header adds it back again..

Minimal example:
https://celvro.github.io/ui-sandbox/

## Steps to Reproduce

1. Create a List with a List Item.
2. Place ToggleSectionHeader with isTransparent in list item.
3. Put button inside of ToggleSectionHeader.
4. Open in Internet Explorer.
5. Open section header, then move your mouse around, it usually happens when you move your mouse off the clickable area of the header.

## Expected Behavior
The margins/padding of section header do not change when moving the mouse in IE.

## Environment

* Component Name and Version: ToggleSectionHeader 1.18.0
* Browser Name and Version: Internet Explorer 11.1.17134.0
* Node/npm Version: node 8.11.3, npm 6.4.0
* Webpack Version: 4.17.1
* Operating System and version (desktop or mobile): Windows 10

**Comment by bjankord** [comment] 2018-08-28 18:59
I'm able to reproduce this when viewing the provided minimal example in IE 11. @celvro Does this issue occur if you use a [terra-button component](https://engineering.cerner.com/terra-ui/#/components/terra-button/button/button) instead of html button element?

**Comment by celvro** [comment] 2018-08-28 20:41
Yes it happens with both <button> and the terra-button component.

I did not see the issue with text only. However if there is text below the button, space is still added to the end of the dropdown, after the text.

If there are multiple buttons on the same line, only one instance of space is added, however if there are line breaks in between the buttons extra space is added for each button.

**Comment by celvro** [comment] 2018-08-28 20:46
Also we did not see this issue when wrapping ToggleSectionHeader in a div instead of the List component.

**Comment by bjankord** [comment] 2018-09-27 20:28
@celvro Does this bug happen when not using the `isTransparent` prop on the ToggleSectionHeader component?

**Comment by celvro** [comment] 2018-09-27 20:31
No it's only with the transparent property set.

**Comment by bjankord** [comment] 2018-12-11 15:46
We are planning to remove the `isTransparent` prop in a major version bump per OCS feedback on this component: https://github.com/cerner/terra-core/issues/1933

**Comment by neilpfeiffer** [comment] 2018-12-11 15:59
Since this bug is only affected by the `isTransparent` prop and we will be removing it per UX request with upcoming work to Section-Header/Toggle-Section-Header, we can leave this issue open, but we do not need to fix, and it will be Closed/Resolved by #1933.

**Closed** 2019-03-06 17:49 UTC
Labels: Orion Reviewed, bug, wontfix
