### ISSUE TITLE
terra-menu flickers when contentWidth is set to auto

### ISSUE THREAD

**Issue by yogeshmuthuraj** [cerner/terra-core#1035] opened 2017-11-22 05:55 UTC
# Issue Description

In terra-menu package, when contentWidth is set to `"auto"`, the opening and closing of the menu is causing flickering.

#### Gif: 
![flickering](https://user-images.githubusercontent.com/15688664/33111963-c53d6df6-cf76-11e7-94f4-ee84bd8a5fac.gif)
## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
The transition of opening and closing of the menu to be smooth.

## Current Behavior

The menu expands to full width for a second and then resizes.

## Steps to Reproduce

1. Include terra-menu in an app
2. ![Try this example code](https://github.com/cerner/terra-core/tree/master/packages/terra-menu/docs)
3. Set the contentWidth to auto , `contentWidth="auto"`

## Environment

* Component Version: terra-menu 1.8.0
* Browser Name and Version: Chrome 62, Fireforx 57, and Safari 10
* Operating System and version (desktop or mobile): MacOS Sierra 10.12

**Comment by msaikaushik1992** [comment] 2017-11-28 20:17
@yogeshmuthuraj I'm not able to reproduce this bug (with Component Version: terra-menu 1.8.0) on Chrome 62, Firefox 57, and Safari 10. It seems to be work fine for me with contentWidth set to "auto". So could you please tell some other ways to reproduce the bug.

**Comment by alecrowen** [comment] 2017-11-30 19:16
Closing this until we get more information.

**Closed by alecrowen** 2017-11-30 19:16 UTC
Labels: bug, menu
