### ISSUE TITLE
Misaligned Rows on Props Table

### ISSUE THREAD

**Issue by dylan-sftwr** [cerner/terra-core#1271] opened 2018-02-20 23:14 UTC
# Issue Description

This very well could not be an issue, as I'm consistently able to produce it in Chrome, but not in Firefox or Safari

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior

All rows within the props-table component should be aligned.

## Current Behavior

When viewing the [Input component's](http://engineering.cerner.com/terra-core/#/site/form/input) props table, I noticed in Chrome that several rows were slightly misaligned.
![image](https://user-images.githubusercontent.com/17390173/36454263-c703904e-1660-11e8-9939-c4cf419c2364.png)

## Steps to Reproduce

1. Open [Input Component's doc site page](http://engineering.cerner.com/terra-core/#/site/form/input) at 100% zoom in Chrome
2. Scroll to the props-table
3. Observe

## Environment

* Component Version: Unknown
* Browser Name and Version: Chrome, 64.0.3282.167
* Operating System and version (desktop or mobile): MacOS Sierra v. 10.12.5

**Comment by alecrowen** [comment] 2018-03-01 19:39
Cant reproduce, won't fix.

**Closed by alecrowen** 2018-03-01 19:39 UTC
Labels: orion reviewed, props-table
