### ISSUE TITLE
Terra Image update not reflecting updates 

### ISSUE THREAD

**Issue by PaulSolDev** [cerner/terra-core#2030] opened 2018-11-08 18:07 UTC
# Bug Report

## Description

Application using the terra image supports a workflow to capture a new/replacement image.  Result of workflow is reflected in that the the image is updated. This worked prior to https://github.com/cerner/terra-core/pull/1971 but now fails to update.
 

## Steps to Reproduce

n/a

## Expected Behavior

Image updates as expected.

## Possible Solution

Either treat as a non passive change and document accordingly for consuming teams OR correct the issue and return to previous functionality. 

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by supreethmr** [comment] 2019-01-29 11:33
@PaulSolDev I was not able to recreate this issue with both terra-core examples and even in sample app created by implementing terra-image to display image. Images were updating as expected onClick() of button. can you please let me know if there any other steps to reproduce this issue.

**Comment by JoeJennings** [comment] 2019-01-30 16:04
The issue is evident with the change #1971 @PaulSolDev references.  To remove the flicker the component is checking whether the src has changed before allowing the image to reload.  However there is a basic flaw in this pattern.  The src (URL) for the image many times does not change, instead the image stored at that source is updated to a different/newer image.

**Comment by supreethmr** [comment] 2019-02-01 08:53
@JoeJennings  Can you please let me know steps to recreate capture new image workflow. Since i am not able to recreate this issue in Terra-core and Example app. The workflow which I Tried is, I created app with Image component and assigned it's source property with url of image A before loading and Image A loads as expected and on Button click I changed the source property of image with url of Image B and Image component updates without any error. so I would like to know the steps of workflow in which the above issue is occurring.

**Comment by JoeJennings** [comment] 2019-02-01 21:09
Steps that caused this issue in the demographics details photo capture functionality:

1. Load an image in the Image Component (ProfileImage) by setting the src to a URL endpoint that returns an image/photo.
2. Change the image/photo stored at the URL endpoint so that the URL when exercised returns the new image not the old image.
3. Reload/Refresh the Image Component, the URL endpoint does not change only the photo that it would return; however this code #1971 doesn't allow that refresh to occur because its sees that the URL didn't change.

**Comment by yuderekyu** [comment] 2019-02-08 21:14
@JoeJennings I'm confused, Demographics points to `"terra-image": "^2.2.0"`; the flicker fix is in version `2.25.0`, so Demographics already pulls past that fix. Was Demographics previously locked down to `2.24.0`, which fixed the issue?

To go along with @supreethmr, refreshing the page or calling `forceUpdate()` on the component should trigger another `render()`. [`getDerivedStateFromProps`](https://github.com/cerner/terra-core/blob/master/packages/terra-image/src/Image.jsx#L77-L84) does not block the image from reloading - `render()` is always called right after. 

Is there caching involved with the `src`?

**Comment by yuderekyu** [comment] 2019-02-14 18:39
Closing this - React compares the previous version of the component with the current one and updates based on the result. For a re-render in this case, the props remain unchanged so the DOM node will not be modified. A solution to this is to either pass in a [query url](https://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url) into `src` or have two renders: one that passes in an empty string, then a second that passes in the url.

**Closed by yuderekyu** 2019-02-14 18:39 UTC
Labels: Orion Reviewed, bug, image
