### ISSUE TITLE
[terra-form-select] Red border is missing from invalid form select in fusion theme

### ISSUE THREAD

**Issue by saket2403** [cerner/terra-core#3444] opened 2021-05-20 06:07 UTC
# Bug Report

## Description
A red border is applied to invalid terra-form-select in default theme. But no red border is applied in fusion theme . Consumers want same styles in both themes.

## Steps to Reproduce

1. Change theme to orion-fusion in dev site
2. Check invalid date picker example [here](https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/select).
3.
4.

## Expected Behavior
A red border should be applied for invalid selects in fusion theme.

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

## @ Mentions
@ryanthemanuel @neilpfeiffer

**Comment by neilpfeiffer** [comment] 2021-05-20 14:18
@saket2403 Please see the comment on [terra-core/issues/3427](https://github.com/cerner/terra-core/issues/3427#issuecomment-830158015) which gives the explanation as to why the `orion-fusion-theme` intentionally does not have red borders on the form elements when they are set to `isInvalid` by design.

Will close as duplicate and won't fix unless there are any additional concerns.

**Comment by ryanthemanuel** [comment] 2021-05-24 14:07
Closing per @neilpfeiffer's comments.

**Closed by ryanthemanuel** 2021-05-24 14:07 UTC
Labels: :package: terra-form-select, wontfix
