### ISSUE TITLE
LoadingOverlay does not work in modal dialog 

### ISSUE THREAD

**Issue by ps022884** [cerner/terra-core#2805] opened 2020-01-21 11:57 UTC
# Bug Report

## Description
LoadingOverlay is not working when the view is of type modal dialog

## Steps to Reproduce

  if (true) {
    content  = <OverlayContainer overlay={<LoadingOverlay isOpen={isLoading} isAnimated backgroundStyle="clear"/>}/>; 
  } else if (isFailed) {
    content = <StatusView variant={StatusViewVariants.ERROR} message={intl.formatMessage({ id: 'alert-history-engine.alert-history-failed-to-load' })} isGlyphHidden />;
  } else if (text && text.length > 0) {
    content = <Spacer paddingTop="large+1" paddingBottom="large+1" paddingLeft="large+1" paddingRight="large+1">{text}</Spacer>;
  } else {
    content = <StatusView variant={StatusViewVariants.NODATA} message={intl.formatMessage({ id: 'alert-history-engine.no-alert-history' })} isGlyphHidden />;
  }

  return (
    <DialogModal
    ariaLabel="Dummy Modal"
    isOpen={true}
    header={<ActionHeader title="Dummy"  />}
    footer={
      <ActionFooter  
        end={<Button text="Close"  />}
      />
    }
   
    width="1600"
  >
     {[ content ]}
  </DialogModal>

## Additional Context / Screenshots
![LoadingOverlay](https://user-images.githubusercontent.com/60129800/72802732-711ebe80-3c72-11ea-9216-3c1beefa9c3a.jpeg)

## Expected Behavior
On Loading expecting the Overlay to animate

**Comment by saket2403** [comment] 2020-01-23 15:10
Is this a feature that should be provided, I had look at this [thread](https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1579269551733?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1579269551733&teamName=Terra&channelName=Component%20Support&createdTime=1579269551733) cc @StephenEsser @neilpfeiffer

**Comment by ShettyAkarsh** [comment] 2020-01-24 05:20
@ps022884  as suggested by @neilpfeiffer in this [thread](https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1579269551733?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1579269551733&teamName=Terra&channelName=Component%20Support&createdTime=1579269551733). did you try using terra-modal-manager here instead of Dialog Modal ?

**Comment by ps022884** [comment] 2020-01-24 07:45
Sure @ShettyAkarsh  , i can try using  terra-modal-manager and see if that can resolve the issue.

**Comment by ps022884** [comment] 2020-01-27 05:01
@ShettyAkarsh and @neilpfeiffer  , i re-checked the mock screen designed by UX designer ,which we are developing and its mentioned to use Modal dialog . Is it not possible to solve this overlay issue for modal dialog?

**Comment by neilpfeiffer** [comment] 2020-01-27 11:26
This is not a bug - implementation shown above is incorrect.

Dialog-modal was created primary for fluid/wrapping text content, and was built for it's height to grow when given content, but that content needs to have a fixed height. Your implementation gives the dialog-modal only a `<OverlayContainer overlay={}/>;` as content, which has no set height (OverlayContainer is just a relatively positioned div, and Overlay by default is set to 100%, but dialog-modal needs content with fixed pixel height, not percentage). 

A working example to put a loading animation inside of a dialog-modal if needed would be:
```
<DialogModal
  ariaLabel="Your Label that describes the modal"
  isOpen={this.state.isOpen}
  onRequestClose={this.handleCloseModal}
  header={<ActionHeader title="Action Header here" onClose={this.handleCloseModal} />}
  footer={<ActionFooter end="Footer Buttons here" />}
  >     
    <OverlayContainer
        className={cx('my-fixed-size-for-overlay-container')}
        overlay={<LoadingOverlay isOpen isAnimated isRelativeToContainer backgroundStyle="clear" message="" id="MyDialogLoadingOverlay" />}
    />
</DialogModal>
```
where you will need to add additional css to either apply a fixed height to the overlay container, and/or a parent div around all the content with a set min-height:
 ```
  .my-fixed-size-for-overlay-container {
    width: 100%;
    height: 240px;
  }
```

The result will have the loading overlay correctly showing in the dialog-modal:

<img width="607" alt="Screen Shot 2020-01-27 at 4 47 36 AM" src="https://user-images.githubusercontent.com/1355485/73171048-72624800-40c5-11ea-9073-3e4d5f15e90f.png">

**Comment by neilpfeiffer** [comment] 2020-01-27 11:27
Closing as not an issue

**Closed by neilpfeiffer** 2020-01-27 11:27 UTC
Labels: not an issue

**Comment by neilpfeiffer** [comment] 2020-01-27 11:40
>  i re-checked the mock screen designed by UX designer ,which we are developing and its mentioned to use Modal dialog . Is it not possible to solve this overlay issue for modal dialog?

@ps022884 Based on the designs that Nanda Kishore has shown me, the callouts you have received are incorrect and Dialog-Modal is an improper component to use, since as I mentioned above, it's intent is for only simple text based content, not fully structured ui designed (tables, slide-panels, etc.). A Modal-Manager with a set height and width will be a more appropriate component to use in your case. 

Overlays & LoadingOverlays do work with-in both Dialog-Modals and Modal-Managers using the `isRelativeToContainer` prop, exactly like to the example given above. The only difference in implementation between them, is for Dialog-Modal you need to provide a rigid pixel dimension height (e.g. 240px), vs. for Modal-Manager you can use the 100% percentage height because the regular modal has a rigid parent size.
