### ISSUE TITLE
Error Pages Component (terra-consumer)

### ISSUE THREAD

**Issue by javalkar-varun** [cerner/terra-core#745] opened 2017-08-24 13:35 UTC
# Issue Description

The Terra Consumer Error Page is a display presented with an error message and location for a button on a Card component.

## Issue Type

- [x] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior

The Error Page component will show Error icon, Error message and button. A button will provide a user with primary and secondary action.

There are different types of error pages:
- Not Authorized Error Page: 
This page will always have a "Not Authorized" text and rest (icon, message, and button) are optional.
- Sensitive concept Error Page:
This page will always have a "Sensitive Data" text and rest (icon, message, and button) are optional.
- Error Page:
This page will always have an "Error" text and rest (icon, message, and button) are optional.

### Considerations:
- Cover most of the Cerner [Terra Clinical Error View ](http://engineering.cerner.com/terra-clinical/#/site/error-view)

### Example:
```
import React from 'react';
import ErrorPages from 'terra-core-error-pages';
import Button from 'terra-button';

<ErrorPages
  name="error name"
  description="error description"
  buttonText="error button text"
  buttonOnClick={this.handleClick();}
  isGlyphHidden={false}
 />

This will require creating new files:
/terra-core/packages/terra-core-error-pages/src/ErrorPages.jsx
/terra-core/packages/terra-core-error-pages/src/ErrorIcon.jsx
/terra-core/packages/terra-core-error-pages/src/ErrorPages.scss
```

### Props table:
Prop Name | Type | Is Required | Default Value | Description
-- | -- | -- | -- | --
name | string | required | '' | The name of the error to display.
description | string | optional | '' | The error description to display.
buttonOnClick | func | optional | undefined | The click callback function that should be applied to the button.
buttonText | string | optional | '' | The display text for the button.
isGlyphHidden | bool | optional | false | Whether or not the error glyph should be displayed.

### CSS Classes:
Selector | Description
-- | --
well-Icon-large well-text--light | Icon styling
well-Font-xxx--large well-text--light | Icon text style
well-Font--body well-text--large | message style
terra-Button terra-Button--default well-Font--large well-Button--concept3 well-Button--fill | Terra Button style

**Comment by javalkar-varun** [comment] 2017-08-24 14:15
Do I have to load error page component on the terra-card component? I'm assuming whoever is using Error Page component, will be using it on top of terra-card. So Error Page component doesn't have to import terra-card?

**Comment by emilyrohrbough** [comment] 2017-08-24 14:18
If this is a terra-consumer component, should could we log this issue in the [terra-consumer repo](https://github.com/cerner/terra-consumer/issues)?

**Comment by javalkar-varun** [comment] 2017-08-24 14:25
Sure, created - https://github.com/cerner/terra-consumer/issues/16

**Comment by alex-bezek** [comment] 2017-08-24 14:30
No, I think this should take the terra-clinical component, move it to terra-core, and theme/enhance it properly to solve the existing terra-clinical look/feel (legacy), consumer theme, and OCS theme. I think the code will end up in terra-core.

**Comment by alex-bezek** [comment] 2017-08-24 17:38
@javalkar-varun, you called out that there are 3 kinds of errors, but i'm curious how you intend to flex the message and icon for each? Based off your current props, the text is passed in by the consumer, but the icon isn't configurable. Should there be some type enum that can determine the icon/text? Is the text going to be consistent for specific types, or should that stay configurable via a prop?

For the prop `buttonOnClick` consumer and OCS callouts have multiple buttons. Sync up with @amf9t2 and any of the questions he is tracking down from UX concerning these buttons. You can probably solve the issue in the same manner.

You can probably remove the css selector portion of your tech design. I don't think thats required all the time now.  And you appear to have some funkiness going on using the wellness prefix along with specific wellness helper classes for font.

Concerning your question about card, I think it would be ideal if the consumer didn't have to compose this on a card as it appears this component has a designated amount of spacing between the contents and the card edge, so it would be nice if it was done consistently in this package. Although you will have to figure out a good way to make the card then themeable as legacy (whats in clinical right now) doesn't utilize a card. 

The card also brings up a question around both this and @amf9t2 's component. I don't see any specific callouts for this, but it seems the card is a fixed width at all times. When there is lots of text it wraps instead of pushing the card wider. When very little text is there, it doesn't shrink down.

**Comment by neilpfeiffer** [comment] 2017-08-25 09:23
@javalkar-varun @amf9t2 @alex-bezek: cross posting this same comment on both issues for coverage:
- [terra-core#744](https://github.com/cerner/terra-core/issues/744)
- [terra-core#745](https://github.com/cerner/terra-core/issues/745) duplicates [terra-consumer#16](https://github.com/cerner/terra-consumer/issues/16)
---

Let's pause on theme styling issues for a moment, I will confirm the css details needed for the theme versions next and how Legacy/Clinical/Consumer are expecting them to be presented (in a card/container vs. a built-in shape around component, etc.).

There is a good possibility we should merge `No Data` and `Error View` in one package due to matching presentation and consistency in functional API -- I want to discuss it in post-scrum or warroom Friday to confirm. But, we also may need to have two packages, one for terra-core and extended for terra-consumer OR sister packages in terra-clinical and terra-consumer (none in core) due to type differences. Here is the current list of react props I've identified after talking with both teams:

### `type` 
enum, current requirements are they will be different for consumer than clinical
- Clinical:  (1)No Data, (2)No Matching Results, (3)Not Authorized, (4)Error _/\*confirmed list\*/_
- Consumer: (1)No Data, (2)No Matching Results, (3)Not Authorized, (4)Error, (5)Sensitive Data, (6) custom _/\*team is confirming list on Friday\*/_

### `customIcon` 
element
- For consumer only, allowing for `type.CUSTOM` to provide a custom image

### `customTitle`
string,  _currently_ `heading`, `name`
- Clinical confirmed they would like the title/heading not exposed as available prop, standard translations would be provided and text gets added always based on `type`
- Consumer will be confirming if they will follow same pattern with fixed strings for their 5 defined types, allowing for react prop to be exposed but only used for `type.CUSTOM`.

### `text`
string, _currently_ `subtext`, `description`
- Both Clinical and Consumer confirmed as available prop to take a message.
- I'm wondering if actual usage will ever need to put more complex content in the message like we needed for Alert (including HTML, a reference link, etc.) and this should accept _node_ rather than _string_, but suggest leaving that for a future enhancement unless others have thoughts. Other option is to have a general `children` prop that you pass the message and any actions as a _node_

### `actions` or `children`
node, similar to current `subtextContent ` and `buttonText`+`buttonOnClick `
- needs more thinking and definition as to best way to solve, plus correct naming
- basically need one or more props to handle including multiple actions, buttons 

### `isIconHidden` 
bool, _currently_ `isGlyphHidden`, no change
- might rename to `isIconHidden` or `isImageHidden` if making new package/s _(confirming naming convention of what is a 'glyph', 'icon', 'image')_
- Both Clinical and Consumer confirmed the flexibility to hide the glyph/icon/image by manual config in addition to automatically with sizing

**Comment by tm4027** [comment] 2017-08-25 14:34
Orion reviewed

**Comment by alex-bezek** [comment] 2017-08-28 13:28
After discussing in our war room, it was decided that this component and the `No Data View` https://github.com/cerner/terra-core/issues/744 component should be combined into 1 called `Status View` https://github.com/cerner/terra-core/issues/752
Closing this issue to consolidate issues into 1.

**Closed by alex-bezek** 2017-08-28 13:28 UTC
Labels: Needs Orion review, new feature, tech design

**Comment by PaulSolDev** [comment] 2017-11-20 16:26
Orion JIRA created
