### ISSUE TITLE
[terra-content-container] Adds gap in IE 11

### ISSUE THREAD

**Issue by Me999999999** [cerner/terra-core#2924] opened 2020-04-13 14:57 UTC
# Bug Report

## Description
When a toggle-section-header is open in IE 11, a gap of blank space is added at the bottom of the content. This gap increases the more content is in the section header or the more headers that are open. This error occurs both with the isTransparent prop set to true and false.

## Steps to Reproduce
1. Create a terra-toggle-section-header, with large amount of content
2. Open the terra-toggle-section-header in IE 11

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/23201118/79130175-1fb33680-7d6c-11ea-9871-506322b7d965.png)

## Expected Behavior
No extra spacing should be added.

## Environment

* Component Name and Version: terra-toggle-section-header v2.32.0
* Browser Name and Version: IE 11
* Node/npm Version: npm 5.6.0
* Webpack Version: 4.42.0
* Operating System and version (desktop or mobile): desktop

**Comment by ryanthemanuel** [comment] 2020-04-14 15:01
@Me999999999 can you send us a code snippet of how you're consuming this component?

**Comment by Me999999999** [comment] 2020-04-24 20:08
`
<ContentContainer>
  <ToggleSectionHeader isTransparent >
            <li>Line 1</li>
              <ul>Line 2</ul>
            <li>Line 3</li>
              <ul>Line 4</ul>
            <li>Line 5</li>
              <ul>Line 6</ul>
            <li>Line 7</li>
              <ul>Line 8</ul>
  </ToggleSectionHeader>
</ContentContainer>
`
This is an example that shows the issue

**Comment by pranav300** [comment] 2020-04-28 19:12
With my initial investigation, this issue seems to be caused by `ContentContainer`. The reason behind it would be `main and normalizer` CSS classes for the variant `static` of prop `fill`.

**Comment by Me999999999** [comment] 2020-04-28 20:25
The ContentContainer we are specifically using when experienceing this error only has the header prop defined so it does not have fill set to true

**Comment by ryanthemanuel** [comment] 2020-05-19 12:11
@Me999999999 and @dkasper-was-taken worked through some fixes for this on the consuming side. Closing this for now. If it’s still an issue we can open up a new issue.

**Closed by ryanthemanuel** 2020-05-19 12:11 UTC
