### ISSUE TITLE
[terra-overlay] [terra-content-container] Height issue - LoadingOverlay within Modal

### ISSUE THREAD

**Issue by juliacalandro** [cerner/terra-core#2828] opened 2020-01-31 17:21 UTC
# Bug Report

## Description
I need a LoadingOverlay to display as transparent over the full body of a ContentContainer that is within a modal. The modal has been disclosed via ModalManager. The issue I'm running into is that the height of the LoadingOverlay is only the height of the area between the header and footer of the ContentContainer. When the body of the ContentContainer is scrollable, the LoadingOverlay does not cover the full height of the body. The gif within "Additional Context/Screenshots" demonstrates this.

## Steps to Reproduce
This is the structure of the components within the Modal component that gets disclosed:
```jsx
<ContentContainer fill header={<Header />} footer={<Footer />}>
    <LoadingOverlay
            backgroundStyle={LoadingOverlay.Opts.BackgroundStyles.LIGHT}
            isOpen
            isAnimated
            isRelativeToContainer
    />
    <div>
        <ModalContent1 />
        <ModalContent2 />
    </div>
</ContentContainer>
```

## Additional Context / Screenshots
The screen recording gif demonstrating this issue can be accessed in [Sharepoint](https://cernerprod-my.sharepoint.com/:i:/g/personal/jc046438_cerner_net/EZpSSRnLjO9FmQy7vj2l9usBVTBmdw6RpTiMdsnz6ai-BA?e=bGwOEC).

## Expected Behavior
The LoadingOverlay fills the full height of the scrollable area within the ContentContainer.

## Environment

* Component Name and Version:
terra-content-container (3.21.0)
terra-overlay (3.36.0) (specifically LoadingOverlay)
terra-modal-manager (6.20.0)
* Browser Name and Version: Chrome
* Node/npm Version: 79.0.3945.79 (Official Build) (64-bit)
npm 6.12.1
node 10.16.0
* Webpack Version: 4.41.2
* Operating System and version (desktop or mobile):
Mac Mojave Version 10.14.6
Desktop

**Comment by juliacalandro** [comment] 2020-01-31 17:24
This might not be a bug with any of the components. This issue is also for asking how to fix the UI problem, if possible, with styling or changes to the implementation code.

**Comment by tbiethman** [comment] 2020-01-31 17:43
The problem is occurring because your example is rendering the LoadingOverlay within a scrollable element (provided by the ContentContainer). You'll need change how you're rendering that overlay to avoid this.

```jsx
import OverlayContainer from 'terra-overlay/lib/OverlayContainer';
import Scroll from 'terra-scroll';

<ContentContainer fill header={<Header />} footer={<Footer />}>
  <OverlayContainer 
    style={{ height: '100%' }} // Make a class for this, but a 100% height here prevents the ContentContainer's scrollable element from scrolling
    overlay={(
      <LoadingOverlay
        backgroundStyle={LoadingOverlay.Opts.BackgroundStyles.LIGHT}
        isOpen
        isAnimated
        isRelativeToContainer
      />
    )}
  >
    <Scroll> // This Scroll element adds a scrollable element back into the flow so that your contents can overflow appropriately
      <ModalContent1 />
      <ModalContent2 />
    </Scroll>
  </OverlayContainer>
</ContentContainer>
```

Structuring the components like this will ensure that the Overlay itself is rendered adjacent to (not inside of) the scrollable element.

The ModalManager provided by terra-application (and orion-application internally) provides APIs for loading overlay presentation that takes these issues into account. If you're using those versions, consider using the ApplicationLoadingOverlay component instead: http://engineering.cerner.com/terra-application/components/terra-application/application/reference/components/modal-manager#loading-overlays

**Comment by juliacalandro** [comment] 2020-01-31 18:31
Ah will try that! Thanks!

**Comment by juliacalandro** [comment] 2020-02-03 19:07
Both solutions that you provided worked, thanks!

**Comment by ryanthemanuel** [comment] 2020-02-04 15:50
Closing this since the solutions worked.

**Closed by ryanthemanuel** 2020-02-04 15:50 UTC
Labels: overlay, question
