### ISSUE TITLE
[terra-props-table] intl proptype not getting pulled in correctly in generated dev site

### ISSUE THREAD

**Issue by ag030750** [cerner/terra-core#1678] opened 2018-07-05 17:32 UTC
# Bug Report

## Description

Terra-doc-template does not mark the intl prop as required when creating the prop table for a component.

## Steps to Reproduce

1. Use intl prop in component and mark it as required.
2. Setup the dev site for repo such that the prop table is auto generated.
3. Run the dev site.

## Additional Context / Screenshots

<img width="1139" alt="screen shot 2018-07-05 at 12 08 02 pm" src="https://user-images.githubusercontent.com/40867287/42337541-be014990-804c-11e8-9723-bfe234d7feb9.png">

## Expected Behavior

The prop table on the dev site should mark intl as required.

**Comment by emilyrohrbough** [comment] 2018-07-06 02:06
@ag030750 Do you have an example implementation of the issue you are seeing? Neither terra-doc-template nor terra-props-table are internationalized components so `intl` is not a required prop to render either.

**Comment by bjankord** [comment] 2019-02-06 14:46
Closing as more info is needed to debug. If this is still an issue, leave a comment and we can re-open.

**Comment by tbiethman** [comment] 2019-04-04 16:44
This was brought up again during our regular office hours. The issue is that the terra-props-table output does not show that the `intl` prop is required, even if `isRequired` is used for the propType definition. This is seen with the docs for terra-clinical-data-grid, where the `intl` prop is required but shows as optional in the props table: https://engineering.cerner.com/terra-ui/#/components/terra-clinical-data-grid/clinical-data-grid/clinical-data-grid

**Closed** 2019-04-11 21:28 UTC
Labels: Orion Reviewed, intermediate issue
