### ISSUE TITLE
[terra-demographics-banner] Uplift to the controlled responsive element

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-core#2962] opened 2020-05-11 20:13 UTC
# Feature Request

## Description
Investigate uplifting the terra-demographics-banner onto the controlled responsive element or alternative. 

## Description

The uncontrolled responsive element has been [flagged for deprecation](https://github.com/cerner/terra-core/pull/2729). The terra-demographics-banner should either be uplifting onto the controlled responsive element implementation or alternatively the responsive element should be removed from the component.

**Comment by StephenEsser** [comment] 2020-05-11 20:21
Duplicate of https://github.com/cerner/terra-core/issues/2673. These issues can probably be merged into a single issue

**Comment by ryanthemanuel** [comment] 2020-05-12 14:54
Closing this as duplicate of #2673

**Closed by ryanthemanuel** 2020-05-12 14:54 UTC
Labels: demographics banner
